# Generated by Django 5.0.2 on 2024-03-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0004_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reports_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
